$filePath = "d:\AntiGravityWorkSpace\TheOddLabs2.0\src\engine\overworld.js"
$content = Get-Content $filePath
$before = $content[0..2313]
$after = $content[2415..($content.Length-1)]
$newLines = @(
"        if (npc.id === 'jenzi') {",
"            if (!window.gameState.storyFlags.starterChosen) {",
"                // Starter selection flow",
"                lines = [",
"                    'Welcome to the trenches, Intern! I''m Jenzi, your guide through this corporate fever dream.',",
"                    'We''re supposedly ''healing the world,'' but mostly we''re just trying not to get fired by Lab Director Capsain.',",
"                    'This floor is only a tiny slice of the National Lab mega-structure, though.',",
"                    'We only handle a few departments here—Botanic, Human Research, and the Executive Suite.',",
"                    'Since you''re the new main character, you need a Companion Cell.',",
"                    'It''s like a smart pet, but way more... liquid.',",
"                    'We use them for everything—from heavy lifting to high-end research...',",
"                    '...though most researchers just end up teaching them tricks during lunch.',",
"                    'Their origins are a whole rabbit hole of lab theories, but basically everyone loves them.',",
"                    'Well, except for... actually, don''t worry about that yet.',",
"                    'Just know they''re the ultimate lab partners.',",
"                    'I''ve got three in the incubator.',",
"                    'It''s a lab tradition—who knows when or why it started...',",
"                    'But everyone who works here must have at least one Companion Cell.',",
"                    'So just pick one that vibe with you the most.'",
"                ];",
"                // Trigger the modal after dialogue closes.",
"                this.pendingBattleEncounter = 'starter_selection';",
"            } else if (!window.gameState.storyFlags.jenziFirstBattleDone) {",
"                lines = [",
"                    'Sheesh, nice pick! Let''s see if you can actually use it though.',",
"                    'Bet you can''t even touch me in a battle. Pelli-it up!'",
"                ];",
"                this.pendingBattleEncounter = 'jenzi_tutorial';",
"            } else if (!this.logsCollected.includes('Log001')) {",
"                lines = [",
"                    'Not bad, not bad. You actually have some skill. No cap.',",
"                    'Oh look, someone''s out here littering again.',",
"                    'Pick up that Datapad next to the Atrium door.',",
"                    'It''s giving... ''lazy researcher'' vibes.'",
"                ];",
"            } else if (!window.gameState.storyFlags.jenziAtriumUnlocked) {",
"                lines = [",
"                    'Aha! A lost Datapad. People here would forget their own heads if they weren''t attached.',",
"                    'Collect ''em and bring ''em to me, okay? I''ll ''officially'' return them to the owners.',",
"                    'Door to the Atrium is open now. Go explore, but don''t get lost in the sauce.'",
"                ];",
"                window.gameState.storyFlags.jenziAtriumUnlocked = true;",
"                this.renderMap();",
"            } else if (logs < 5) {",
"                lines = [",
"                    'Yo, Intern! Keep looking for Datapads.',",
"                    'The doors are locked until you prove you can do basic research.'",
"                ];",
"            } else if (logs >= 5 && !window.gameState.storyFlags.jenziAtriumBattleDone) {",
"                lines = [",
"                    'You''ve been busy! 5 Datapads already?',",
"                    'Lowkey impressive.',",
"                    'Then you must smell something fishy about the Incident.',",
"                    'But before I tell you about the ''smell'', let''s see if you''re actually worth it.',",
"                    'My Stemmy is ready to rumble. Pelli-it up!'",
"                ];",
"                this.pendingBattleEncounter = 'jenzi_atrium';",
"            } else if (window.gameState.storyFlags.jenziAtriumBattleDone && !window.gameState.storyFlags.botanicSectorUnlocked) {",
"                lines = [",
"                    'Okay, okay, you got me! You''re actually decent.',",
"                    'Since you won, here''s the tea about ''The Incident''.',",
"                    'Director Capsain says it was an ''Ionization Leak''.',",
"                    'Something about that story just isn''t right...',",
"                    'Well beat me, what do I know.',",
"                    'If you want the real story, go ask Lana in the Botanic wing.',",
"                    'She''s the main character of that floor anyway.',",
"                    'I''ve unlocked the door for you. Keep collecting those logs!'",
"                ];",
"                window.gameState.storyFlags.botanicSectorUnlocked = true;",
"                this.renderMap();",
"            } else if (window.gameState.storyFlags.lanaBattleDone && !window.gameState.storyFlags.humanWardUnlocked) {",
"                lines = [",
"                    'Wait, Lana gave you a key? And she was acting sus?',",
"                    'Sus-picious!',",
"                    'That''s weird af. Maybe things aren''t as simple as ''spicy ozone''.',",
"                    'You should totally go bother Dyzes in Human Research.',",
"                    'He''s chill, but he definitely knows things he''s not saying.'",
"                ];",
"                window.gameState.storyFlags.humanWardUnlocked = true;",
"                this.renderMap();",
"            } else if (window.gameState.storyFlags.dyzesBattleDone && !window.gameState.storyFlags.executiveSuiteUnlocked) {",
"                lines = [",
"                    'Dyzes gave you info on an ''Old Lab''? Okay, now this is getting serious.',",
"                    'No more jokes. You need to confront the final boss himself.',",
"                    'Director Capsain. His room is open.',",
"                    'Go get the truth, Intern.'",
"                ];",
"                window.gameState.storyFlags.executiveSuiteUnlocked = true;",
"                this.renderMap();",
"            } else {",
"                lines = ['Main Character energy! Keep collecting those logs, Intern.'];",
"            }",
"        } else if (npc.id === 'lana') {",
"            if (bossWon) {",
"                lines = [",
"                    'Hmph. Just as I suspected. Your tactical calibration is completely non-existent!',",
"                    'You''re lucky my Cambihil was in a ''passive'' mode, or you''d be more than just extracted.',",
"                    'Go back to the entrance and... and don''t come back until you''ve read at least three field guides! Honestly!'",
"                ];",
"            } else if (!window.gameState.storyFlags.lanaMet) {"
)
$finalContent = $before + $newLines + $after
$finalContent | Set-Content $filePath
